discHub/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('main.urls')),
    path('login',include('user.urls'))
]

main/urls.py
from django.urls import path
from . import views
from user import views as usrviews

urlpatterns = [
    path('', views.home , name='home'),
    path('group/<str:pk>', views.group_view , name='group-view'),
    path('group/topic/<str:pk>', views.topicView , name='topicView'),
    path('create-group', views.groupCreate, name="create-group"),
    path('add-topic/<str:pk>', views.add_topic, name="add_topic"),
    path('message-deletion/<str:pk>', views.delete_message, name="delete_message"),
    path('group-deletion/<str:pk>', views.delete_group, name="delete_group"),
    path('group-update/<str:pk>', views.update_group, name="group_update"),
    path('post-text/',usrviews.creat_text_post, name='create-text-post'),
    path('photo-post/',usrviews.create_photo_post, name='creat_photo_post'),
    path('post-text/<str:pk>/',usrviews.text_post_view, name='text-post-view'),
    path('post-text/<str:pk>/delete-comment',usrviews.delete_comment, name='text-post-view-cmdelete'),
    path('photo_post/<str:pk>/',usrviews.view_photo_post, name='view_photo_post'),
    path('post-text/delete-comment/<str:pk>/',usrviews.photo_comment_delete, name='photo-post-delete'),
    path('photo_post/<str:pk>/delete',usrviews.delete_photo_post, name='delete_photo_post'),
    path('profile/update/<str:usr>/',usrviews.profile_update, name='profile_update'),
    path('profile/<str:usr>/', usrviews.profile, name='profile'),
    path('sign-up/',usrviews.sign_up, name='sign-up'),
    path('logout',usrviews.logout_usr, name='logout'),
    path('like/<str:pk>/',usrviews.photo_like, name='like'),
    path('text-post',views.home_text, name='view-text-post')
   

    
]

main/models.py
from tkinter import CASCADE
from tokenize import group
from venv import create
from django.db import models
from user.models import User
# Create your models here.




class Group(models.Model):
    name = models.CharField(max_length=200)
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User,related_name="participants",blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.name

class Topic(models.Model):
    topic = models.CharField(max_length=100,blank=True,null=True)
    group = models.ForeignKey(Group,on_delete=models.SET_NULL,null=True)
    creater = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    discription = models.TextField(null=True,blank=True)
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.topic[0:50]

class Message(models.Model):
    host = models.ForeignKey(User,on_delete=models.SET_NULL,null=True)
    topic = models.ForeignKey(Topic,on_delete=models.SET_NULL,null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):

        return self.body[0:20]

user/models.py
from email.policy import default
from venv import create
from django.db import models
from django.contrib.auth.models import AbstractUser

class User(AbstractUser):
    dp = models.ImageField(upload_to='static/profile',null=True, blank=True,default='static/profile/person.svg')
    level = models.CharField(max_length=100,null=True,blank=True)
    institution = models.CharField(max_length=100,null=True,blank=True)
    town = models.CharField(max_length=100,null=True,blank=True)
    bio = models.TextField(null=True,blank=True)

class Text_post(models.Model):
    creater = models.ForeignKey(User,on_delete=models.SET_NULL,blank=True,null=True)
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.body[0:60]

class Comment(models.Model):
    creater = models.ForeignKey(User,on_delete=models.CASCADE,blank=True,null=True)
    text_post = models.ForeignKey(Text_post,on_delete=models.CASCADE,blank=True,null=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.text[0:50]

class Photo_post(models.Model):
    creater = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    photo = models.ImageField(upload_to='static/posts')
    text = models.TextField(blank=True,null=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.photo)

class Comment_photo_post(models.Model):
    creater = models.ForeignKey(User,on_delete=models.CASCADE,null=True,blank=True)
    photo_post = models.ForeignKey(Photo_post,on_delete=models.CASCADE,null=True,blank=True)
    text = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return self.text[0:20]

class Likes(models.Model):
    liker = models.ForeignKey(User,on_delete=models.CASCADE)
    post = models.ForeignKey(Photo_post,on_delete=models.CASCADE)
    liked = models.BooleanField(default=False)

main/forms.py
from dataclasses import field, fields
from email.headerregistry import Group
from django.forms import ModelForm
from .models import *
 
class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'


class TopicForm(ModelForm):
    class Meta:
        model = Topic
        fields ='__all__'

main/views.py

from email import message
from multiprocessing import context
from os import name
from pydoc_data import topics
from urllib import request
from django.contrib import messages
from django.shortcuts import render,redirect
from django.contrib.auth.decorators import login_required
from .models import *
from .forms import *
from user.models import *
from main import forms
# Create your views here.
def home(request):
    groups = Group.objects.all()
    text_posts = Text_post.objects.all().order_by('-created')
    photo_post = Photo_post.objects.all().order_by('-created')
    com = Comment_photo_post.objects.all()
    context={
        'groups':groups,
        'inc':0,
        'comments':com,
        'text_posts':text_posts,
        'photo_post':photo_post
    }
    return render(request,'main/home.html',context)

def home_text(request):
    text_posts = Text_post.objects.all().order_by('-created')
    context={
        'text_posts':text_posts,
    }
    return render(request,'main/home-text.html',context)


@login_required(login_url='login-form')
def groupCreate(request):
    form = GroupForm()
    group = Group.objects.all()
    if request.method =='POST':
        name = request.POST.get('namee')
        about = request.POST.get('about')
        f = form.save(commit=False)
        f.name = name
        f.description = about
        f.host = request.user
        f.save()
        f.participants.add(request.user)
        messages.success(request, f'Successively added >> ')
        return redirect("home")
    context = {
        "form":form
    }

    return render(request,'main/groupform.html',context)


def group_view(request,pk):
    group = Group.objects.get(id=pk)
    topics =Topic.objects.filter(group=group).order_by("-created")
    participants = group.participants.all()
    no_of_participants = participants.count()
    print(no_of_participants)
    context={
        "group":group,
        "no_p":no_of_participants,
        "topics":topics
    }
    return render(request,'main/groupView.html',context)

def add_topic(request,pk):
    g = Group.objects.get(id=pk)
    topics =Topic.objects.filter(group=g)
    form = TopicForm()
    count = topics.count()
    
    print(f'topics {count}')
    
    user_topic = request.POST.get('topic')
    if request.method =='POST':
        f = form.save(commit=False)
        f.topic = user_topic
        f.creater = request.user
        f.discription = request.POST.get('about')
        f.group = g
        f.save()
        if not f.creater in  g.participants.all():
            g.participants.add(f.creater)
        return redirect('group-view',g.id)
    context ={
        "form":form,
    }
    return render(request,'main/topic.html',context)   


def topicView(request,pk):
    topics = Topic.objects.get(id=pk)
    messages = Message.objects.filter(topic=topics)
    print(f"hi there you {topics}")
    if request.method == "POST":
        Message.objects.create(
            host = request.user,
            topic = topics,
            body = request.POST.get('body-text')
        )
        
        
        return redirect("topicView",topics.id)
    context={
        "topics":topics,
        "messages":messages
    }

    return render(request,'main/topicView.html',context)

def delete_message(request,pk):
    message = Message.objects.get(id=pk)
    if request.method =='POST':
        message.delete()
        message.error(request,f'message delete')
        return redirect("topicView",message.topic.id)
    context={
        "object":message
    }
    return render(request,'delete.html',context)


def delete_group(request,pk):
    group = Group.objects.get(id=pk)
    if request.method =='POST':
        group.delete()
        return redirect('home')
    context={
        'group':group,
        'object':group
    }
    return render(request,'delete.html',context)

def update_group(request,pk):
    group = Group.objects.get(id=pk)
    form = GroupForm(instance=group)
    if request.method == "POST":
        form = GroupForm(request.POST,instance=group)
        f = form.save(commit=False)
        f.save()
        return redirect('group-view',f.id)
    context ={
        
    }
    return render(request,'main/groupform.html')

templates/main/adhome.html
{% block content %}

{% endblock %}

templates/main/groupView.html
{% extends 'main.html'%}
{% block content %}
{% load static %}


<div style="color: aliceblue;" class="g-container">
    <div class="gp">
        <div style="border-bottom: 1px solid white;" class="group-header">
            <div style="display: flex; align-items: center; justify-content: space-between; overflow: hidden; align-content: center;" class="nm">
                <div><h4>{{ group.name }}</h4></div>
                <div class="add-grup">
                    <a class="btn btn-info" href="{% url 'add_topic' group.id %}">
                        <img src="{% static 'images/icons/plus.svg' %}" alt="">
                        topic</a>
                </div>
            </div>
            <div style="display: flex; justify-content: space-between;" class="dis">
                <div class="admin">
                    <div>created by</div>
                    <small>@{{ group.host}}</small>
                    {% if request.user == group.host %}
                    <small><a href="{% url 'delete_group' group.id %}">delete</a></small>
                    <small><a href="{% url 'group_update' group.id %}">update</a></small>
                    {% endif %}
                </div>
                <div class="members">
                <small><img src="{% static 'images/icons/people.svg' %}" alt=""><span class="badge">{{no_p}}</span> </small>
                    
                </div>

            </div>
           
        </div>
        <div class="ava">
            <h5>Topics available</h5>
        </div>
        <div class="group-topics">
            {% if topics %}
            {% for topic in topics%}
            <div class="group-topic">
                <div class="topic-h">
                    <div style="display: flex; width: 100%;" class="av">
                        <div class="avarter">
                            <img src="./static/images/icons/person.svg" alt="user">
                            
                        </div>
                        <div style="display: flex; justify-content: space-between; width: 90%;">
                            <div>
                                <small style="margin-left:4px ;"><b>@{{topic.creater}}</b> created this topic</small>
                            </div>
                            
                            <div style="float: l;"><small>{{ topic.created|timesince }}</small></div>
                           
                           
                        </div>
                        
                        

                    </div>
                    
                    <h5><a style="text-decoration: none;" href="{% url 'topicView' topic.id %}">{{topic.topic}}</a> </h5>
                </div>
                <div class="topic-ov">
                    <p>
                       {{ topic.description}}
                    </p>
                   
                </div>
                <div class="topic-ft">
                    <small>Disscusion <span class="badge bg-dark">55</span></small>
                </div>
                

            </div>

            {% endfor %}
            {% else %}
            <p>No topics yet would you like to add one ?</p>
            {% endif %}
            </div>

        </div>
       
       
</div>

{% endblock%}

templates/main/groupform.html
{% extends 'main.html'%}
{% block content %}

<div style="width: 500px; background-color: black;" class="topic_form">
    <form action="" method="post">
        {% csrf_token%}
        <div class="lg">
            Create Group
        </div>
        <div class="usr">
            <p>Name</p>           
            <input style="background-color: #555555; border:1px solid#5f9ea0;color: rgb(194, 182, 182);" class="form-control" type="text" name="namee" placeholder="Name" id="">
        </div>
        <div class="usr">
            <p>About</p>
            <textarea style="background-color: #555555; border:1px solid#5f9ea0;color: rgb(194, 182, 182);" class="form-control" name="about" id="" cols="30" placeholder="discribe" rows="10"></textarea>
        </div>
        <div class="bt">
            <button class="btn btn-primary" type="submit">Create</button>
            <a href="{{request.META.HTTP_REFERE}}" class="btn btn-dark" >Cancel</a>
        </div>
    </form>
</div>
<script>
    let name = document.querySelector('#id_name')
    name.className = 'form-control'
</script>

{% endblock %}

templates/main/home-text.html
{% extends 'main.html'%}
{% block content %}
{% load static %}
<style>
   .auth-photo{
                  display: flex;
                  justify-content: center;
                  align-items: center;
              }
  .onmind{
    padding: 5px;
    padding-top: 1rem;
    padding-bottom: 1rem;
    background-color: rgb(193, 150, 233);
    border-radius: 20px;
  }
  .feeds{
    margin-top: 2rem;
  }
  .p{
    width: 60px;
    cursor: pointer;
  }
  .post{
    border-radius: 10px;
  }
</style>
<div style="margin-top: 6rem;" class="page">
  <div style="background-color: rgb(108, 166, 218);" class="left-side">
      <h2>side</h2>
      <input class="form-control" type="text" name="" id="">
  </div>
  
      <div  class="home-feeds">
        <div style="background-color: rgb(226, 220, 220); padding: 1rem;"  class="auth-photo">
          <div style="width: 60px; height: 60px;" class="photo me-2">
              <img class="photo-dp" src="{{ user.dp.url}}" alt="" srcset="">
          </div>
          <div class="onmind">
            <a style="text-decoration: none; color: #000;" href="{% url 'create-text-post' %}"> <small>What's on your mind {{request.user}}</small></a>
           
          </div>
          <div class="p">
            <a href="{% url 'creat_photo_post' %}"><img style="width: 100%;" src="./static/images/icons/file-image-fill.svg" alt=""></a>
            
          </div>
      </div>
  
  <div style="margin-top: 1.5rem;"  class="view">
    <a class="btn btn-outline-secondary" href="{% url 'home' %}">view photo posts</a>
    <a class="btn btn-outline-secondary" href="">Browse Group</a>
  </div>
  <div class="feeds">

{% for text_post in text_posts %}
<div style="margin-bottom: 1rem; background-color: #e8eaf0; border-radius: 10px; max-width: 600px; margin: auto;" class="text-post">
  <div style="justify-content: flex-start; padding: 4px;" class="auth-photo">
    <div style="width: 60px; height: 60px;" class="photo me-2">
        <img  class="photo-dp" src="{{text_post.creater.dp.url}}" alt="" srcset="">
    </div>
<small class="">Posted by {{text_post.creater}}</small>

</div>
<small style="margin:1rem;">{{text_post.created|timesince}}</small>
<div class="text-area">
  <p style="padding: 0.5rem;">{{ text_post.body}}</p>
</div>
</div>
<br>
<br>
{% endfor %}

  </div>
      </div>
      <div class="right-side">
        <h1>right</h1>
    </div>
    
    </div>
    
{% endblock %}

templates/main/home.html
{% extends 'main.html'%}
{% block content %}
{% load static %}
<style>
   .auth-photo{
                  display: flex;
                  justify-content: center;
                  align-items: center;
              }
  .onmind{
    padding: 5px;
    padding-top: 1rem;
    padding-bottom: 1rem;
    background-color: rgb(193, 150, 233);
    border-radius: 20px;
  }
  .feeds{
    margin-top: 2rem;
  }
  .p{
    width: 60px;
    cursor: pointer;
  }
  .post{
    border-radius: 10px;
  }
</style>
<div style="margin-top: 6rem;" class="page">
  <div style="background-color: rgb(108, 166, 218);" class="left-side">
      <h2>side</h2>
      <input class="form-control" type="text" name="" id="">
  </div>
  
      <div  class="home-feeds">
        <div style="background-color: rgb(226, 220, 220); padding: 1rem;"  class="auth-photo">
          <div style="width: 60px; height: 60px;" class="photo me-2">
              <img class="photo-dp" src="{{ user.dp.url}}" alt="" srcset="">
          </div>
          <div class="onmind">
            <a style="text-decoration: none; color: #000;" href="{% url 'create-text-post' %}"> <small>What's on your mind {{request.user}}</small></a>
           
          </div>
          <div class="p">
            <a href="{% url 'creat_photo_post' %}"><img style="width: 100%;" src="./static/images/icons/file-image-fill.svg" alt=""></a>
            
          </div>
      </div>
  
  <div style="margin-top: 1.5rem;"  class="view">
    <a class="btn btn-outline-secondary" href="{% url 'view-text-post' %}">view texts posts</a>
    <a class="btn btn-outline-secondary" href="">Browse Group</a>
  </div>
  <div class="feeds">
    {% for photo in photo_post %}
    <div style="background-color: #e8eaf0; padding-bottom: 1rem;" class="post">
      <div style="margin: 0.5rem 0.5rem 0rem 0.5rem;" class="post-header">
        <div  class="auth-photo">
          <div style="width: 60px; height: 60px;" class="photo me-2">
            <a href="{% url 'profile' photo.creater.username %}">
              <img  class="photo-dp" src="{{photo.creater.dp.url}}" alt="" srcset="">
            </a>
             
          </div>
  <small class="">Posted by <a style="text-decoration: none; color: #000;" href="{% url 'profile' photo.creater.username %}"> <b>{{photo.creater}}</b> </a></small>
  
      </div>
      </div>
      <div style="padding-left: 0.5rem;" class="time">
        <small >{{photo.created|timesince}}</small>
      </div>
      <div style="padding: .5rem;" class="post-body">
        <p>{{photo.text}} </p>
      </div>
      <a href="{% url 'view_photo_post' photo.id%}">
      <div style="display: flex; justify-content: center;" class="post-pic">
        <img style="width: auto; max-height: 500px;" src="{{ photo.photo }}" class="img-fluid" alt="...">
      </div>
    </a>
      
    </div>
    <br>
{% endfor%}

  </div>
      </div>
      <div class="right-side">
        <h1>right</h1>
    </div>
    
    </div>
    
{% endblock %}

templates/main/photo-post-view.html
{% extends 'main.html' %}
{% block content %}
{% load static%}
<style>
  .auth-photo{
                 display: flex;
                 justify-content: center;
                 align-items: center;
             }
 .onmind{
   padding: 5px;
   padding-top: 1rem;
   padding-bottom: 1rem;
   background-color: rgb(193, 150, 233);
   border-radius: 20px;
 }
 .feeds{
   margin-top: 2rem;
 }
 .p{
   width: 60px;
   cursor: pointer;
 }
 .post{
   border-radius: 10px;
 }
</style>
<div style="margin-top: 6rem;" class="page">
 <div style="background-color: rgb(108, 166, 218);" class="left-side">
     <h2>side</h2>
     <input class="form-control" type="text" name="" id="">
 </div>
<div class="feeds">
   <div style="background-color: #e8eaf0; padding-bottom: 1rem;" class="post">
     <div style="margin: 0.5rem 0.5rem 0rem 0.5rem; position: relative;" class="post-header">

      
      <div style="position: absolute; right: 0.4rem; top: 0rem;" class="dot">
        <img src="{% static 'images/icons/three-dots.svg' %}" alt="menus">
      </div>
     
      <div class="menus">
        {% if user == item.creater %}
        <a href="{% url 'delete_photo_post' item.id %}"> <img style="height: 1.5rem; margin-bottom: 1rem;" src="{% static 'images/icons/trash3.svg' %}" alt="delete"> </a>
        <a href=""> <img style="height: 1.5rem;" src="{% static 'images/icons/pencil-square.svg' %}" alt=""> </a>
        {% endif %}
      </div>
    
       <div  class="auth-photo">
       
         <div style="width: 60px; height: 60px;" class="photo me-2">
             <img  class="photo-dp" src="{{item.creater.dp.url}}" alt="" srcset="">
         </div>
 <small class="">Posted by <b> <a href="">{{item.creater}}</a> </b></small>
 
     </div>
     </div>
     <div style="padding-left: 0.5rem;" class="time">
       <small >{{item.created|timesince}}</small>
     </div>
     <div style="padding: .5rem;" class="post-body">
       <p>{{item.text}} </p>
     </div>
          <div style="display: flex; justify-content: center;" class="post-pic">
       <img style="width: auto; max-height: 500px;" src="{{ item.photo.url }}" class="img-fluid" alt="...">
     </div>
     
   </div>
   <br>
 </div>

 <div class="right-side">
  <div class="container">
    <h3>comments</h3>
  </div>



  <div class="right-side">
  <div style="background-color: rgb(219, 215, 208); padding: 0.5rem;" class="box">
    <div style="display:flex; align-items:center;"  class="cm-ion">
      <a href="#cm">
      <img style="height:2rem" src="{% static 'images/icons/chat-square-text-fill.svg' %}" alt="icon"></a>
      <h4 style="padding-left: 3px;">{{ no }}</h4>
    
    </div>
  </div>
  {% if comments %}
  {% for comment in comments %}
    <div  style="margin: 0.6rem; display:flex; align-items: flex-start;" class="comment-area">
    
      <div class="auth-photo">
        <div style="min-width:45px ;" class="photo me-2">
            <img class="photo-dp" src="{{ comment.creater.dp.url}}" alt="" srcset="">
        </div>
    
    </div>
    <style>
    </style>
    <div class="comment-body">
      <div style="position: relative;" class="comment-item">
        {% if user == comment.creater or user == item.creater %}
        <div style="position: absolute; right: 0.4rem; top: 0rem;" class="dot">
          <img src="{% static 'images/icons/three-dots.svg' %}" alt="">
        </div>
        <div class="menus">
          <a href="{% url 'photo-post-delete' comment.id %}"> <img style="height: 1.5rem; margin-bottom: 1rem;" src="{% static 'images/icons/trash3.svg' %}" alt="delete"> </a>
          <a href=""> <img style="height: 1.5rem;" src="{% static 'images/icons/pencil-square.svg' %}" alt=""> </a>
        </div>
        {% endif %}
        <a href=""><b><small>@{{comment.creater}}</small></b></a>
      
        <p> {{comment.text}} </p>
      </div>
      <small class="muted">{{comment.created|timesince}}</small>
    </div>
    
    </div>
    {% endfor %}
    {% else %}
   <div style="margin-top: 1rem; display: flex; flex-direction: column; justify-content: center;" class="no-comments">
     <img style="height: 2rem;" src="{% static 'images/icons/chat-square-heart-fill.svg' %}" alt="">
    <center> <small>No comment, be first to comment</small> </center>
    
   </div>
  {% endif %}
  {% if user.is_authenticated %}
   <div class="comment-input">
     <form action="" method="post">
      {% csrf_token %}
     <div id="cm" class="comment-input-area">
       <input class="form-control comment-in" name="body-text" placeholder="Comment" required type="text">
      <button style="background-color: transparent; border: none;" class="btn btn-outline-light" type="submit"><img style="height: 1.5rem; color: red;" src="{% static 'images/icons/send.svg' %}" alt=""></button>
     </div>
    </form>
   </div>
  {% endif %}
  </div>



</div>
     </div>

    <script>
       let dot = document.querySelectorAll('.dot');
        let menus = document.querySelectorAll('.menus');
        let pressed = false;
        // dot.forEach( (x,) =>{
        //   x.addEventListener('click',()=>{
        //     console.log('work')
        //     menus[2].style.display ='flex';
        //   })
        // })
        for(let i =0; i < dot.length;i++){
          dot[i].addEventListener('click',() =>{
            if(pressed){
              menus[i].style.display='none';
              pressed = false;
            }else{
              menus[i].style.display='flex';
              pressed =true;
            }
           
          })
        }
    </script>
  
{% endblock %}

templates/main/photo-post.html
{% extends 'main.html'%}
{% block content %}
<style>
    .page{
      display: grid;
      grid-template-columns: 16rem auto 16rem;
      gap: 2rem;
    }
    @media screen and (max-width:956px) {
      .right-side{
        display: none;
      }
      .page{
        grid-template-columns: 16rem auto;
        gap: 1rem;
      }
      .row{
        margin-right: 1rem;
      }
    }
    @media screen and (max-width: 600px) {
      .page{
          display: flex;
          flex-direction: column;
          padding: 1rem;
      }
      .left-side{
          display: none;
      }
    }
     
    </style>

<div style="margin-top: 4rem;" class="page bg-light">
    <div style="background-color: rgb(240, 243, 245);" class="left-side">
      <div class="container">
          <div class="auth-photo me-2">
          
              <div style="width: 70px;height: 70px;" class="photo me-2">
                  <a href="{% url 'profile' user %}"><img class="photo-dp" src="{{ user.dp.url }}" alt="" srcset=""></a>
                  
              </div>
      <small class="text-white"><span>@</span>
          <a href="{% url 'profile' user %}">{{user.username}}</a> </small>
          </div>
          <h3>{{user.first_name}}</h3>
      </div>
     
    </div>
    
    <div style="margin-top: 1rem;" class="photo-post">
        <div style="max-width: 500px; margin: auto;">
          <h3>Upload a Photo</h3>
          <form enctype="multipart/form-data" method="post">
              {% csrf_token %}
          <div style="margin-top: 1rem;" class="col">
            <p style="font-weight:500;">Browse photo</p>
            {{forms.photo}}
          </div>
        
       
          <div style="margin-top: 2rem;" class="col">
            <p style="font-weight:500;">Your feeling</p>
           {{forms.text}}
          </div>
          <button style="margin-top:1rem" class="btn btn-outline-success" type="submit">upload</button>
        </form>
        </div>
         
      </div>
        
    <div class="right-side">
        <h1>right</h1>
    </div>
<script>
    let name = document.querySelector('#id_name')
    let foto = document.querySelector('#id_photo');
    foto.className='form-control';
    foto.Required
    let txt = document.querySelector('#id_text');
    txt.className='form-control'
    txt.style.border='1px solid #5f9ea0'
    txt.style.backgroundColor='#f2f2f2f2'

    foto.style.backgroundColor = '#f2f2f2f2'
    foto.style.border = '1px solid #5f9ea0'
    name.className = 'form-control'
</script>

{% endblock %}

templates/main/text-post.html
{% extends 'main.html'%}
{% block content %}
<style>
    .page{
      display: grid;
      grid-template-columns: 16rem auto 16rem;
      gap: 2rem;
    }
    @media screen and (max-width:956px) {
      .right-side{
        display: none;
      }
      .page{
        grid-template-columns: 16rem auto;
        gap: 1rem;
      }
      .row{
        margin-right: 1rem;
      }
    }
    @media screen and (max-width: 600px) {
      .page{
          display: flex;
          flex-direction: column;
          padding: 1rem;
      }
      .left-side{
          display: none;
      }
    }
     
    </style>

<div style="margin-top: 4rem;" class="page bg-light">
    <div style="background-color: rgb(240, 243, 245);" class="left-side">
      <div class="container">
          <div class="auth-photo me-2">
          
              <div style="width: 70px;height: 70px;" class="photo me-2">
                  <a href="{% url 'profile' %}"><img class="photo-dp" src="{{ user.dp.url }}" alt="" srcset=""></a>
                  
              </div>
      <small class="text-white"><span>@</span>
          <a href="{% url 'profile' %}">{{user.username}}</a> </small>
          </div>
          <h3>{{user.first_name}}</h3>
      </div>
     
    </div>
    

    <div style="margin-top: 1rem;" class="photo-post">
        <div style="max-width: 500px; margin: auto;">
          <h3>Share your feeling</h3>
          <form method="post">
              {% csrf_token %}
          <div style="margin-top: 2rem;" class="col">
            <p style="font-weight:500;">Your feeling</p>
           {{form.body}}
          </div>
          <button style="margin-top:1rem" class="btn btn-outline-success" type="submit">Share</button>
        </form>
        </div>
         
      </div>

        
    <div class="right-side">
        <h1>right</h1>
    </div>
<script>
    let name = document.querySelector('#id_body')
    let foto = document.querySelector('#id_photo');
    name.className='form-control';
    name.rows='5'
    let txt = document.querySelector('#id_text');
    txt.className='form-control'
    txt.style.border='1px solid #5f9ea0'
    txt.style.backgroundColor='#f2f2f2f2'

    foto.style.backgroundColor = '#f2f2f2f2'
    foto.style.border = '1px solid #5f9ea0'
    name.className = 'form-control'
</script>


{% endblock %}